## Build geth from source from a local directory called go-ethereum.

FROM golang:1-alpine as builder

RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Default local client path: clients/go-ethereum/<go-ethereum>
ARG local_path=go-ethereum
COPY $local_path go-ethereum

RUN pwd
RUN ls -la
WORKDIR /go/go-ethereum
RUN apk add --update bash curl jq git make gcc libc-dev linux-headers
ENV DLV=true
RUN make geth
# RUN go build -gcflags="all=-N -l" -o ./build/bin/geth ./cmd/geth
RUN mv ./build/bin/geth /usr/local/bin/geth

FROM alpine:latest
RUN apk add --update bash curl jq
COPY --from=builder /usr/local/bin/geth /usr/local/bin/geth
COPY --from=builder /go/bin/dlv /usr/local/bin/dlv
ENV DLV=true

# Generate the version.txt file.
RUN /usr/local/bin/geth console --exec 'console.log(admin.nodeInfo.name)' --maxpeers=0 --nodiscover --dev 2>/dev/null | head -1 > /version.txt

# Inject the startup script.
ADD geth.sh /geth.sh
ADD mapper.jq /mapper.jq
RUN chmod +x /geth.sh

# Inject the enode id retriever script.
RUN mkdir /hive-bin
ADD enode.sh /hive-bin/enode.sh
RUN chmod +x /hive-bin/enode.sh

# Add a default genesis file.
ADD genesis.json /genesis.json

# Export the usual networking ports to allow outside access to the node
EXPOSE 8545 8546 8547 8551 30303 30303/udp 2345

ENTRYPOINT ["/geth.sh"]
