- client: go-ethereum
  nametag: multicall-git
  dockerfile: git
  build_args:
    github: ethereum/go-ethereum
    tag: master

- client: nethermind
  nametag: multicall-git
  dockerfile: git
  build_args:
    github: NethermindEth/nethermind
    tag: eth_simulate_v1

- client: reth
  nametag: multicall-git
  dockerfile: git
  build_args:
    github: paradigmxyz/reth
    tag: main
